//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Perechislenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перечисление.
    /// </summary>
    // *** Start programmer edit section *** (перечисление CustomAttributes)

    // *** End programmer edit section *** (перечисление CustomAttributes)
    public enum перечисление
    {
        
        // *** Start programmer edit section *** (перечисление.1 CustomAttributes)

        // *** End programmer edit section *** (перечисление.1 CustomAttributes)
        [Caption("11")]
        1 = 1,
        
        // *** Start programmer edit section *** (перечисление.2 CustomAttributes)

        // *** End programmer edit section *** (перечисление.2 CustomAttributes)
        [Caption("22")]
        2 = 2,
    }
}
